### ISSUE TITLE
Rmpi - "Function not implemented"

### ISSUE THREAD

**Issue by mvsfrazao** [PacktPublishing/Mastering-Parallel-Programming-with-R#1]
Dear sirs,

I´ve followed the instructions for Rmpi installation through the link below 
http://www.stats.uwo.ca/faculty/yu/Rmpi/windows.htm

but when I try to set up workers:
mpi.spawn.Rslaves()

It returns an error message: 

"Error in mpi.comm.spawn(slave = system.file("Rslaves64.cmd", package = "Rmpi"),  : 
  Other MPI error, error stack:
MPI_Comm_spawn(cmd="C:/Program Files/R/R-3.3.1/library/Rmpi/Rslaves64.cmd", argv=0x000000001C4D7090, maxprocs=8, MPI_INFO_NULL, root=0, MPI_COMM_SELF, intercomm=0x000000000C27DC60, errors=0x000000001C7C0318) failed
Function not implemented"

But when I run in a DOS terminal:

C:\Program Files\Microsoft MPI\Bin> mpiexec  -n 9 "C:\Program Files\R\R-3.3.1\bin\x64\Rterm.exe" --no-save -q

master (rank 0, comm 1) of size 9 is running on: DESKTOP-1OJENRN
slave1 (rank 1, comm 1) of size 9 is running on: DESKTOP-1OJENRN
slave2 (rank 2, comm 1) of size 9 is running on: DESKTOP-1OJENRN
slave3 (rank 3, comm 1) of size 9 is running on: DESKTOP-1OJENRN
... ... ...
slave7 (rank 7, comm 1) of size 9 is running on: DESKTOP-1OJENRN
slave8 (rank 8, comm 1) of size 9 is running on: DESKTOP-1OJENRN

Is there anything that I´m missing?

Thanks in advance!

**Comment by techsachinkumar** [comment]
Hi mvsfrazao

Did you try installing Rmpi again?
Was your issue resolved?

Regards
